### Importing the library

In [193]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

### Importing the dataset [URL](https://grouplens.org/datasets/movielens/)

In [194]:
df_rating=pd.read_csv("ratings.csv")

#### Exploratory Data Analysis

In [195]:
df_rating.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [196]:
df_rating.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

#### Statistical Overview

In [197]:
df_rating.describe()

userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [198]:
df_rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
userId       100836 non-null int64
movieId      100836 non-null int64
rating       100836 non-null float64
timestamp    100836 non-null int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


#### Selected columns

In [199]:
col_rating=["userId","movieId","rating"]

#### Importing Movies dataset

In [200]:
df_movies=pd.read_csv("movies.csv")

In [201]:
df_movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [202]:
df_movies.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  
9737  Action|Animation|Comedy|Fantasy  
9738         Animation|Comedy|Fantasy  
9739                            Drama  
9740                 Action|Animation  
9741                           Comedy

In [203]:
df_movies.describe()

movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [204]:
df_movies.describe(include="all")

movieId        title genres
count     9742.000000         9742   9742
unique            NaN         9737    951
top               NaN  Eros (2004)  Drama
freq              NaN            2   1053
mean     42200.353623          NaN    NaN
std      52160.494854          NaN    NaN
min          1.000000          NaN    NaN
25%       3248.250000          NaN    NaN
50%       7300.000000          NaN    NaN
75%      76232.000000          NaN    NaN
max     193609.000000          NaN    NaN

In [205]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
movieId    9742 non-null int64
title      9742 non-null object
genres     9742 non-null object
dtypes: int64(1), object(2)
memory usage: 228.4+ KB


In [206]:
df_movies.count

<bound method DataFrame.count of       movieId                                              title  \
0           1                                   Toy Story (1995)   
1           2                                     Jumanji (1995)   
2           3                            Grumpier Old Men (1995)   
3           4                           Waiting to Exhale (1995)   
4           5                 Father of the Bride Part II (1995)   
5           6                                        Heat (1995)   
6           7                                     Sabrina (1995)   
7           8                                Tom and Huck (1995)   
8           9                                Sudden Death (1995)   
9          10                                   GoldenEye (1995)   
10         11                     American President, The (1995)   
11         12                 Dracula: Dead and Loving It (1995)   
12         13                                       Balto (1995)   
13         14  

#### Columns Movies

In [207]:
col_movies=["movieId","title"]

#### combine movies and rating dataset based on movies id

In [208]:
df_mr=pd.merge(df_rating[col_rating],df_movies[col_movies],how='left',left_on="movieId",right_on="movieId")

In [209]:
df_mr.head()

userId  movieId  rating                        title
0       1        1     4.0             Toy Story (1995)
1       1        3     4.0      Grumpier Old Men (1995)
2       1        6     4.0                  Heat (1995)
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)
4       1       50     5.0   Usual Suspects, The (1995)

In [210]:
df_mr.tail()

userId  movieId  rating                           title
100831     610   166534     4.0                    Split (2017)
100832     610   168248     5.0   John Wick: Chapter Two (2017)
100833     610   168250     5.0                  Get Out (2017)
100834     610   168252     5.0                    Logan (2017)
100835     610   170875     3.0  The Fate of the Furious (2017)

In [211]:
df_mr.count

<bound method DataFrame.count of         userId  movieId  rating                                      title
0            1        1     4.0                           Toy Story (1995)
1            1        3     4.0                    Grumpier Old Men (1995)
2            1        6     4.0                                Heat (1995)
3            1       47     5.0                Seven (a.k.a. Se7en) (1995)
4            1       50     5.0                 Usual Suspects, The (1995)
5            1       70     3.0                 From Dusk Till Dawn (1996)
6            1      101     5.0                       Bottle Rocket (1996)
7            1      110     4.0                          Braveheart (1995)
8            1      151     5.0                             Rob Roy (1995)
9            1      157     5.0                      Canadian Bacon (1995)
10           1      163     5.0                           Desperado (1995)
11           1      216     5.0                       Billy Madison

In [212]:
df_mr.describe()

userId        movieId         rating
count  100836.000000  100836.000000  100836.000000
mean      326.127564   19435.295718       3.501557
std       182.618491   35530.987199       1.042529
min         1.000000       1.000000       0.500000
25%       177.000000    1199.000000       3.000000
50%       325.000000    2991.000000       3.500000
75%       477.000000    8122.000000       4.000000
max       610.000000  193609.000000       5.000000

In [213]:
df_mr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 0 to 100835
Data columns (total 4 columns):
userId     100836 non-null int64
movieId    100836 non-null int64
rating     100836 non-null float64
title      100836 non-null object
dtypes: float64(1), int64(2), object(1)
memory usage: 3.8+ MB


#### Convert the above data into pivot table matrix form ( wher we are going to consider rows are unique user id and columns are unique movies id)

In [214]:
pvt_table=df_mr.pivot_table(columns=["movieId"],index=["userId"],values="rating")

In [215]:
print(pvt_table)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
6           NaN     4.0     5.0     3.0     5.0     4.0     4.0     3.0   
7           4.5     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
8           NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
9           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
10          NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
11          NaN     NaN     NaN     NaN     NaN     5.0     NaN     NaN   
12          NaN     NaN  

#### In ithe new pivot table we have lot of value is NAN so conver all the NAN value into zero

In [216]:
pvt_table=pvt_table.fillna(0)

In [217]:
print(pvt_table)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6           0.0     4.0     5.0     3.0     5.0     4.0     4.0     3.0   
7           4.5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8           0.0     4.0     0.0     0.0     0.0     0.0     0.0     0.0   
9           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10          0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
11          0.0     0.0     0.0     0.0     0.0     5.0     0.0     0.0   
12          0.0     0.0  

#### As we know pandas is built on Numpy so better we will convert it into numpy format for faster execution

In [218]:
data_matrix=pvt_table.as_matrix()

C:\Users\Sanjeev\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [219]:
data_matrix

array([[4. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 2. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 0. , ..., 0. , 0. , 0. ]])

### Recomendation engine for content based filtering

#### 1.  User - user similiraty matrix

In [220]:
from scipy.spatial.distance import cosine

In [221]:
m,n=data_matrix.shape

In [222]:
m

610

In [223]:
n

9724

In [224]:
data_matrix

array([[4. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 2. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 0. , ..., 0. , 0. , 0. ]])

#### User Similiraty matrix

In [225]:
mat_users=np.zeros((m,m))

In [226]:
mat_users

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [227]:
for i in range(m):
    for j in range(m):
        if i!=j:
            mat_users[i][j]=(1-cosine(data_matrix[i,:],data_matrix[j,:]))
        else:
            mat_users[i][j]=0
            

In [228]:
pd_users=pd.DataFrame(mat_users, index=pvt_table.index, columns=pvt_table.index)

#### Finding the similar users relevent to the cosine functionality

In [229]:
def topSimUsers(uid=10,n=6):
    users=pd_users.loc[uid,:].sort_values(ascending=False)
    topn_users=users.iloc[:n,]
    topn_users=topn_users.rename('score')
    print("Similar users as user:",uid)
    return pd.DataFrame(topn_users)
print(topSimUsers(uid=1,n=5))

Similar users as user: 1
           score
userId          
266     0.357408
313     0.351562
368     0.345127
57      0.345034
91      0.334727


#### Most rated movies of the users 

In [230]:
def topRatedMovies(userid=50,n_ratings=10):
    userid_ratings=df_mr.loc[df_mr["userId"]==userid]
    userid_ratings=userid_ratings.sort_values(by="rating",ascending=[False])
    print("Top",n_ratings,"movie ratings of users:",userid)
    return userid_ratings.iloc[:n_ratings,]
print(topRatedMovies(userid=10,n_ratings=5))

Top 5 movie ratings of users: 10
      userId  movieId  rating                          title
1258      10   140110     5.0              The Intern (2015)
1167      10     8869     5.0          First Daughter (2004)
1236      10    96079     5.0                 Skyfall (2012)
1229      10    91529     5.0  Dark Knight Rises, The (2012)
1161      10     7458     5.0                    Troy (2004)
